site_name: Eduardo Furlan
site_author: Eduardo Furlan
copyright: CC BY 4.0 License
repo_name: efurlanm
repo_url: http://github.com/efurlanm/
use_directory_urls: false  # need for inline html and dir navigation
docs_dir: docs-src
site_dir: docs
theme:
    name: material
    palette:
#https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
        primary: white
        accent: white
    features:
        - header.autohide
markdown_extensions:
    - def_list
    - md_in_html
    - tables
extra_css:
    - css/extra.css
plugins:
    - search
    - blog:
        post_readtime: false
exclude_docs: |
    .ipynb_checkpoints
    .git
nav:
    - 'research.md'
    - 'teaching.md'
    - 'publications.md'
    - 'links.md'
    - Blog:
        - blog/index.md
    - 'index.md'
