# Last edited: 2025-06-28
site_name: "Eduardo Furlan"
site_description: Eduardo Furlan's Home
site_author: Eduardo Furlan
site_url: https://efurlanm.github.io/
# repo_name: efurlanm
# repo_url: https://www.github.com/efurlanm/
# copyright: CC BY 4.0 License
use_directory_urls: false
docs_dir: src
site_dir: docs
theme:
    # squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    name: material
    palette:
        primary: white
        accent: white
    font: false
       #text: Lato
       #code: Lato Mono
    features:
        - header.autohide
        - navigation.tracking   # address shows active anchor
    icon:
        logo: material/account-outline
    # https://www.iconarchive.com/show/material-icons-by-pictogrammers/account-outline-icon.html
    favicon: img/account-outline.ico
plugins:
    # - search
    - blog:
        post_readtime: false
extra:
    generator: false            # "Made with Material for MkDocs"
extra_css:
    - assets/extra.css
    - assets/katex/katex.min.css
extra_javascript:
    - assets/katex.js
    - assets/katex/katex.min.js
    - assets/katex/contrib/auto-render.min.js
markdown_extensions:
    - tables
    #- md_in_html  # allows for writing Markdown inside of HTML
    - pymdownx.arithmatex:
        generic: true           # katex
    - pymdownx.snippets:        # mkdocs-macros-plugin
        check_paths: true
        base_path: src/include
not_in_nav: |
    assets/
    include/
    books/
    courses.md
    pub-all.md
    pub-courses.md
    teach-gallery.md
    teach-project.md
    teach-pdesc.md
nav:
    - Home: index.md
    - Research: research.md
    - Teaching: teaching.md
    - Engineering: engineering.md
    - Notes: notes.md
    - Blog:
      - blog/index.md
exclude_docs: |
    .*
    *§*
    *#*
